import type { Review } from "@/features/reviews/types/review.types";

export const mockReviews: Review[] = [
  {
    id: "fleur-1",
    productId: "fleur-de-lune",
    customerName: "Amelia R.",
    rating: 5,
    comment: "Luminous and soft on the skin, with a beautiful jasmine trail.",
    date: "2026-02-14",
  },
  {
    id: "fleur-2",
    productId: "fleur-de-lune",
    customerName: "Nadia K.",
    rating: 4,
    comment: "Elegant and airy. The white musk lasts beautifully into the evening.",
    date: "2026-01-30",
  },
  {
    id: "fleur-3",
    productId: "fleur-de-lune",
    customerName: "Clara M.",
    rating: 5,
    comment: "A graceful floral that never becomes too sweet.",
    date: "2025-12-08",
  },
  {
    id: "santal-1",
    productId: "santal-parchment",
    customerName: "Thomas B.",
    rating: 5,
    comment: "Warm, polished sandalwood with a wonderfully calm dry-down.",
    date: "2026-02-02",
  },
  {
    id: "santal-2",
    productId: "santal-parchment",
    customerName: "Elena P.",
    rating: 4,
    comment: "Cardamom gives this a refined lift. Perfect for cooler days.",
    date: "2026-01-19",
  },
  {
    id: "santal-3",
    productId: "santal-parchment",
    customerName: "Marcus L.",
    rating: 5,
    comment: "Smooth, intimate, and remarkably well blended.",
    date: "2025-11-21",
  },
  {
    id: "noir-1",
    productId: "noir-cocoon",
    customerName: "Sofia D.",
    rating: 5,
    comment: "A deep amber cocoon with just the right amount of tobacco.",
    date: "2026-02-20",
  },
  {
    id: "noir-2",
    productId: "noir-cocoon",
    customerName: "Julian W.",
    rating: 3,
    comment: "Rich and atmospheric, though I prefer it in small doses.",
    date: "2026-01-12",
  },
  {
    id: "noir-3",
    productId: "noir-cocoon",
    customerName: "Iris G.",
    rating: 4,
    comment: "Velvety amber that feels especially beautiful at night.",
    date: "2025-12-16",
  },
  {
    id: "sol-1",
    productId: "sol-dor",
    customerName: "Maya S.",
    rating: 5,
    comment: "Fresh sea salt and bright bergamot make this effortless to wear.",
    date: "2026-02-11",
  },
  {
    id: "sol-2",
    productId: "sol-dor",
    customerName: "Daniel A.",
    rating: 4,
    comment: "Clean, coastal, and subtle without disappearing too quickly.",
    date: "2026-01-04",
  },
  {
    id: "atelier-1",
    productId: "atelier-oud",
    customerName: "Layla H.",
    rating: 5,
    comment: "The saffron gives the oud a luminous, luxurious finish.",
    date: "2026-02-24",
  },
  {
    id: "atelier-2",
    productId: "atelier-oud",
    customerName: "Omar N.",
    rating: 4,
    comment: "Powerful and beautifully textured. A little goes a long way.",
    date: "2026-01-27",
  },
  {
    id: "atelier-3",
    productId: "atelier-oud",
    customerName: "Rania E.",
    rating: 5,
    comment: "A statement oud with an unexpectedly soft finish.",
    date: "2025-12-04",
  },
  {
    id: "rose-1",
    productId: "rose-absolute",
    customerName: "Hannah V.",
    rating: 5,
    comment: "The rose feels natural and velvety, grounded beautifully by cedar.",
    date: "2026-02-07",
  },
  {
    id: "rose-2",
    productId: "rose-absolute",
    customerName: "Noor T.",
    rating: 4,
    comment: "Romantic without being sugary, with lovely lasting power.",
    date: "2026-01-16",
  },
  {
    id: "rose-3",
    productId: "rose-absolute",
    customerName: "Beatrice C.",
    rating: 5,
    comment: "A sophisticated rose I reach for whenever I want to feel polished.",
    date: "2025-11-29",
  },
];
